//! Markdown reporter — designed for PR comments.
//!
//! Compact, scannable, with a heading and a violation
//! table. The output is GitHub-flavoured Markdown that renders cleanly
//! as a PR comment via `gh pr comment` or as a body posted by a CI
//! workflow.

use std::io::Write;

use anyhow::Result;

use rustics::MetricSeverity;

use crate::report::{Report, Violation};
use crate::reporters::ReportOptions;

/// Writes the Markdown form of `report` to `out` with default options.
/// Embedding-host convenience.
#[allow(dead_code)] // public convenience API; the CLI uses `write_with`.
pub fn write(report: &Report, out: &mut dyn Write) -> Result<()> {
    write_with(report, &ReportOptions::lean(), out)
}

/// Like [`write`] but with `--explain <metric-id>` honoured: each
/// matching violation gets a collapsible `<details>` block with its
/// rationale + refactor hints under the table, so PR readers can
/// expand individual lenses without drowning the comment.
pub fn write_with(report: &Report, opts: &ReportOptions, out: &mut dyn Write) -> Result<()> {
    write_heading(report, out)?;
    if report.violations.is_empty() {
        writeln!(out, "_No violations._")?;
        return Ok(());
    }
    write_table(&report.violations, out)?;
    write_inline_explanations(&report.violations, opts, out)?;
    write_footer(report, out)?;
    Ok(())
}

/// Emits one `<details>` block per violation whose lens was named in
/// `--explain`. Collapsible so the markdown comment stays scannable.
fn write_inline_explanations(
    violations: &[Violation],
    opts: &ReportOptions,
    out: &mut dyn Write,
) -> Result<()> {
    for v in violations {
        if opts.should_explain(&v.metric) {
            write_one_explanation(v, out)?;
        }
    }
    Ok(())
}

fn write_one_explanation(v: &Violation, out: &mut dyn Write) -> Result<()> {
    writeln!(
        out,
        "<details><summary>{} — {} ({})</summary>\n",
        v.metric, v.scope, v.id
    )?;
    if let Some(rationale) = &v.rationale {
        writeln!(out, "{rationale}\n")?;
    }
    write_explanation_hints(&v.refactor_hints, out)?;
    writeln!(out, "</details>\n")?;
    Ok(())
}

fn write_explanation_hints(hints: &[String], out: &mut dyn Write) -> Result<()> {
    if hints.is_empty() {
        return Ok(());
    }
    writeln!(out, "**Refactor hints:**")?;
    for h in hints {
        writeln!(out, "- {h}")?;
    }
    writeln!(out)?;
    Ok(())
}

fn write_heading(report: &Report, out: &mut dyn Write) -> Result<()> {
    writeln!(
        out,
        "## rustics — {} violation(s)",
        report.summary.violations
    )?;
    writeln!(
        out,
        "_files analysed: {}; warnings: {}; errors: {}; generated: {}_",
        report.summary.files_analyzed,
        report.summary.warnings,
        report.summary.errors,
        report.generated_at,
    )?;
    writeln!(out)?;
    Ok(())
}

fn write_table(violations: &[Violation], out: &mut dyn Write) -> Result<()> {
    writeln!(
        out,
        "| Severity | File:Line | Scope | Metric | Value | Threshold | Justified |"
    )?;
    writeln!(
        out,
        "|----------|-----------|-------|--------|-------|-----------|-----------|"
    )?;
    for v in violations {
        writeln!(
            out,
            "| {sev} | `{file}:{line}` | `{scope}` | `{metric}` | {value} | {threshold} | {justified} |",
            sev = severity_word(v.severity),
            file = v.file,
            line = v.line,
            scope = v.scope,
            metric = v.metric,
            value = format_number(v.value),
            threshold = format_number(v.threshold),
            justified = justified_cell(v),
        )?;
    }
    writeln!(out)?;
    Ok(())
}

/// `_96.5% line cov_` for justified, empty otherwise. Italic so a
/// reader can scan the table and ignore the justified ones.
fn justified_cell(v: &Violation) -> String {
    let Some(j) = &v.complexity_justified else {
        return String::new();
    };
    let basis = match j.by {
        crate::report::JustificationBasis::Line => "line",
        crate::report::JustificationBasis::Branch => "branch",
    };
    format!("_{:.1}% {basis} cov_", j.actual * 100.0)
}

fn write_footer(report: &Report, out: &mut dyn Write) -> Result<()> {
    if report.truncated > 0 {
        writeln!(
            out,
            "_…and {n} more violations dropped by `--limit`._",
            n = report.truncated
        )?;
        writeln!(out)?;
    }
    writeln!(
        out,
        "<sub>generated by `cargo rustics analyze --reporter md`. \
         see `cargo rustics manual` for the lens catalogue.</sub>"
    )?;
    Ok(())
}

fn severity_word(s: MetricSeverity) -> &'static str {
    match s {
        MetricSeverity::Error => "🔴 error",
        MetricSeverity::Warning => "🟡 warning",
        MetricSeverity::Info => "ℹ️ info",
    }
}

fn format_number(v: f64) -> String {
    if (v - v.trunc()).abs() < f64::EPSILON {
        format!("{}", v as i64)
    } else {
        format!("{v:.2}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::report::{Summary, Violation};
    use rustics::ScopeKind;

    fn fixture() -> Report {
        Report {
            version: 1,
            generated_at: "T".into(),
            summary: Summary {
                files_analyzed: 1,
                violations: 1,
                warnings: 1,
                errors: 0,
                warnings_justified: 0,
                errors_justified: 0,
            },
            violations: vec![Violation {
                id: "abc".into(),
                file: "src/x.rs".into(),
                line: 42,
                scope: "f".into(),
                scope_kind: ScopeKind::FreeFunction,
                metric: "cyclomatic-complexity".into(),
                value: 14.0,
                threshold: 10.0,
                severity: MetricSeverity::Warning,
                rationale: None,
                refactor_hints: vec![],
                references: vec![],
                rust_context: Default::default(),
                complexity_justified: None,
            }],
            truncated: 0,
            measurements: vec![],
            stale_dismissals: vec![],
        }
    }

    #[test]
    fn heading_includes_violation_count() {
        let mut buf = Vec::new();
        write(&fixture(), &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("## rustics — 1 violation(s)"));
    }

    #[test]
    fn table_renders_each_violation() {
        let mut buf = Vec::new();
        write(&fixture(), &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("`src/x.rs:42`"));
        assert!(s.contains("`cyclomatic-complexity`"));
        assert!(s.contains("warning"));
    }

    #[test]
    fn empty_report_says_no_violations() {
        let r = Report {
            violations: vec![],
            summary: Summary {
                files_analyzed: 5,
                violations: 0,
                warnings: 0,
                errors: 0,
                warnings_justified: 0,
                errors_justified: 0,
            },
            ..fixture()
        };
        let mut buf = Vec::new();
        write(&r, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("_No violations._"));
    }

    #[test]
    fn truncation_renders_dropped_count() {
        let mut r = fixture();
        r.truncated = 3;
        let mut buf = Vec::new();
        write(&r, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("3 more violations dropped"));
    }

    #[test]
    fn explain_metrics_emits_collapsible_details_block() {
        // The dartrics-port `--explain <metric-id>` flag arrives at the
        // md reporter as `opts.explain_metrics`. The rationale and
        // hints must show up inside a collapsible <details> block per
        // matching violation, under the table.
        use std::collections::HashSet;
        let mut r = fixture();
        r.violations[0].rationale = Some("paragraph A\nparagraph B".into());
        r.violations[0].refactor_hints = vec!["hint one".into(), "hint two".into()];
        let mut explain = HashSet::new();
        explain.insert("cyclomatic-complexity".to_string());
        let opts = ReportOptions {
            auto_explain: false,
            explain_metrics: explain,
        };
        let mut buf = Vec::new();
        write_with(&r, &opts, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("<details><summary>cyclomatic-complexity"));
        assert!(s.contains("paragraph A"));
        assert!(s.contains("paragraph B"));
        assert!(s.contains("**Refactor hints:**"));
        assert!(s.contains("- hint one"));
        assert!(s.contains("- hint two"));
        assert!(s.contains("</details>"));
    }

    #[test]
    fn explain_metrics_skips_violation_for_unmatched_lens() {
        use std::collections::HashSet;
        let mut r = fixture();
        r.violations[0].rationale = Some("must not appear".into());
        let mut explain = HashSet::new();
        explain.insert("clone-density".to_string());
        let opts = ReportOptions {
            auto_explain: false,
            explain_metrics: explain,
        };
        let mut buf = Vec::new();
        write_with(&r, &opts, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(!s.contains("<details>"));
        assert!(!s.contains("must not appear"));
    }

    #[test]
    fn explain_metrics_handles_violation_without_hints() {
        // A violation can have a rationale but empty `refactor_hints`;
        // the **Refactor hints:** header must NOT appear in that case
        // (write_explanation_hints early-returns).
        use std::collections::HashSet;
        let mut r = fixture();
        r.violations[0].rationale = Some("only rationale, no hints".into());
        r.violations[0].refactor_hints = vec![];
        let mut explain = HashSet::new();
        explain.insert("cyclomatic-complexity".to_string());
        let opts = ReportOptions {
            auto_explain: false,
            explain_metrics: explain,
        };
        let mut buf = Vec::new();
        write_with(&r, &opts, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("only rationale, no hints"));
        assert!(!s.contains("**Refactor hints:**"));
    }

    #[test]
    fn info_severity_renders_emoji_word_in_table() {
        // Reachable via `--from-clippy` (clippy `note` level). The md
        // reporter renders an emoji-prefixed severity word per row.
        let mut r = fixture();
        r.violations[0].severity = MetricSeverity::Info;
        let mut buf = Vec::new();
        write(&r, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("ℹ️ info"), "expected info emoji+word, got: {s}");
    }

    #[test]
    fn error_severity_renders_emoji_word_in_table() {
        // The other two arms in severity_word — Error renders the red
        // dot, Warning renders the yellow dot. Smoke-test both.
        let mut r = fixture();
        r.violations[0].severity = MetricSeverity::Error;
        let mut buf = Vec::new();
        write(&r, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("🔴 error"), "expected error emoji+word, got: {s}");
    }

    #[test]
    fn justified_cell_renders_basis_and_percent() {
        // The Justified column was added in the complexityJustified port.
        // Both `Line` and (the reserved) `Branch` basis variants must
        // render with their basis word + percent.
        use crate::report::{ComplexityJustification, JustificationBasis};
        let line = Violation {
            complexity_justified: Some(ComplexityJustification {
                by: JustificationBasis::Line,
                threshold: 0.95,
                actual: 0.965,
            }),
            ..fixture().violations.into_iter().next().unwrap()
        };
        assert_eq!(justified_cell(&line), "_96.5% line cov_");
        let branch = Violation {
            complexity_justified: Some(ComplexityJustification {
                by: JustificationBasis::Branch,
                threshold: 0.80,
                actual: 0.85,
            }),
            ..fixture().violations.into_iter().next().unwrap()
        };
        assert_eq!(justified_cell(&branch), "_85.0% branch cov_");
        // No justification → empty cell.
        assert_eq!(justified_cell(&fixture().violations[0]), "");
    }
}
