//! Markdown reporter — designed for PR comments.
//!
//! Plan §7.2. Compact, scannable, with a heading and a violation
//! table. The output is GitHub-flavoured Markdown that renders cleanly
//! as a PR comment via `gh pr comment` or as a body posted by a CI
//! workflow.

use std::io::Write;

use anyhow::Result;

use rustics::MetricSeverity;

use crate::report::{Report, Violation};

/// Writes the Markdown form of `report` to `out`.
pub fn write(report: &Report, out: &mut dyn Write) -> Result<()> {
    write_heading(report, out)?;
    if report.violations.is_empty() {
        writeln!(out, "_No violations._")?;
        return Ok(());
    }
    write_table(&report.violations, out)?;
    write_footer(report, out)?;
    Ok(())
}

fn write_heading(report: &Report, out: &mut dyn Write) -> Result<()> {
    writeln!(
        out,
        "## rustics — {} violation(s)",
        report.summary.violations
    )?;
    writeln!(
        out,
        "_files analysed: {}; warnings: {}; errors: {}; generated: {}_",
        report.summary.files_analyzed,
        report.summary.warnings,
        report.summary.errors,
        report.generated_at,
    )?;
    writeln!(out)?;
    Ok(())
}

fn write_table(violations: &[Violation], out: &mut dyn Write) -> Result<()> {
    writeln!(
        out,
        "| Severity | File:Line | Scope | Metric | Value | Threshold |"
    )?;
    writeln!(
        out,
        "|----------|-----------|-------|--------|-------|-----------|"
    )?;
    for v in violations {
        writeln!(
            out,
            "| {sev} | `{file}:{line}` | `{scope}` | `{metric}` | {value} | {threshold} |",
            sev = severity_word(v.severity),
            file = v.file,
            line = v.line,
            scope = v.scope,
            metric = v.metric,
            value = format_number(v.value),
            threshold = format_number(v.threshold),
        )?;
    }
    writeln!(out)?;
    Ok(())
}

fn write_footer(report: &Report, out: &mut dyn Write) -> Result<()> {
    if report.truncated > 0 {
        writeln!(
            out,
            "_…and {n} more violations dropped by `--limit`._",
            n = report.truncated
        )?;
        writeln!(out)?;
    }
    writeln!(
        out,
        "<sub>generated by `cargo rustics analyze --reporter md`. \
         see `cargo rustics manual` for the lens catalogue.</sub>"
    )?;
    Ok(())
}

fn severity_word(s: MetricSeverity) -> &'static str {
    match s {
        MetricSeverity::Error => "🔴 error",
        MetricSeverity::Warning => "🟡 warning",
        MetricSeverity::Info => "ℹ️ info",
    }
}

fn format_number(v: f64) -> String {
    if (v - v.trunc()).abs() < f64::EPSILON {
        format!("{}", v as i64)
    } else {
        format!("{v:.2}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::report::{Summary, Violation};
    use rustics::ScopeKind;

    fn fixture() -> Report {
        Report {
            version: 1,
            generated_at: "T".into(),
            summary: Summary {
                files_analyzed: 1,
                violations: 1,
                warnings: 1,
                errors: 0,
            },
            violations: vec![Violation {
                id: "abc".into(),
                file: "src/x.rs".into(),
                line: 42,
                scope: "f".into(),
                scope_kind: ScopeKind::FreeFunction,
                metric: "cyclomatic-complexity".into(),
                value: 14.0,
                threshold: 10.0,
                severity: MetricSeverity::Warning,
                rationale: None,
                refactor_hints: vec![],
                references: vec![],
                rust_context: Default::default(),
            }],
            truncated: 0,
            measurements: vec![],
        }
    }

    #[test]
    fn heading_includes_violation_count() {
        let mut buf = Vec::new();
        write(&fixture(), &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("## rustics — 1 violation(s)"));
    }

    #[test]
    fn table_renders_each_violation() {
        let mut buf = Vec::new();
        write(&fixture(), &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("`src/x.rs:42`"));
        assert!(s.contains("`cyclomatic-complexity`"));
        assert!(s.contains("warning"));
    }

    #[test]
    fn empty_report_says_no_violations() {
        let r = Report {
            violations: vec![],
            summary: Summary {
                files_analyzed: 5,
                violations: 0,
                warnings: 0,
                errors: 0,
            },
            ..fixture()
        };
        let mut buf = Vec::new();
        write(&r, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("_No violations._"));
    }

    #[test]
    fn truncation_renders_dropped_count() {
        let mut r = fixture();
        r.truncated = 3;
        let mut buf = Vec::new();
        write(&r, &mut buf).unwrap();
        let s = String::from_utf8(buf).unwrap();
        assert!(s.contains("3 more violations dropped"));
    }
}
